apiVersion: 1
datasources:
  - id: 1
    uid: "[new-uid]"
    orgId: 1
    name: "Firebolt-Monitor"
    type: "yesoreyeram-infinity-datasource"
    url: ""
    basicAuth: false
    basicAuthUser: ""
    isDefault: true
    jsonData:
      allowedHosts:
        - "https://my-firebolt-engine.firebolt.eu-central-1.app.firebolt.io"
      auth_method: "bearerToken"
      global_queries: []
      oauthPassThru: false
      secureQueryName1: "database"
    readOnly: false
    secureJsonData:
      bearerToken: "xxxxxxx"
      secureQueryValue1: "xxxxxxx"